/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsOhmRouteImport } from './routes/tests-ohm'
import { Route as TeoriaOhmRouteImport } from './routes/teoria-ohm'
import { Route as TeoriaKirchhoffRouteImport } from './routes/teoria-kirchhoff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CursoSlugCourseIdRouteImport } from './routes/curso.$slug.$courseId'

const TestsOhmRoute = TestsOhmRouteImport.update({
  id: '/tests-ohm',
  path: '/tests-ohm',
  getParentRoute: () => rootRouteImport,
} as any)
const TeoriaOhmRoute = TeoriaOhmRouteImport.update({
  id: '/teoria-ohm',
  path: '/teoria-ohm',
  getParentRoute: () => rootRouteImport,
} as any)
const TeoriaKirchhoffRoute = TeoriaKirchhoffRouteImport.update({
  id: '/teoria-kirchhoff',
  path: '/teoria-kirchhoff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CursoSlugCourseIdRoute = CursoSlugCourseIdRouteImport.update({
  id: '/curso/$slug/$courseId',
  path: '/curso/$slug/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teoria-kirchhoff': typeof TeoriaKirchhoffRoute
  '/teoria-ohm': typeof TeoriaOhmRoute
  '/tests-ohm': typeof TestsOhmRoute
  '/category/$slug': typeof CategorySlugRoute
  '/curso/$slug/$courseId': typeof CursoSlugCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teoria-kirchhoff': typeof TeoriaKirchhoffRoute
  '/teoria-ohm': typeof TeoriaOhmRoute
  '/tests-ohm': typeof TestsOhmRoute
  '/category/$slug': typeof CategorySlugRoute
  '/curso/$slug/$courseId': typeof CursoSlugCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teoria-kirchhoff': typeof TeoriaKirchhoffRoute
  '/teoria-ohm': typeof TeoriaOhmRoute
  '/tests-ohm': typeof TestsOhmRoute
  '/category/$slug': typeof CategorySlugRoute
  '/curso/$slug/$courseId': typeof CursoSlugCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/teoria-kirchhoff'
    | '/teoria-ohm'
    | '/tests-ohm'
    | '/category/$slug'
    | '/curso/$slug/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/teoria-kirchhoff'
    | '/teoria-ohm'
    | '/tests-ohm'
    | '/category/$slug'
    | '/curso/$slug/$courseId'
  id:
    | '__root__'
    | '/'
    | '/teoria-kirchhoff'
    | '/teoria-ohm'
    | '/tests-ohm'
    | '/category/$slug'
    | '/curso/$slug/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeoriaKirchhoffRoute: typeof TeoriaKirchhoffRoute
  TeoriaOhmRoute: typeof TeoriaOhmRoute
  TestsOhmRoute: typeof TestsOhmRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CursoSlugCourseIdRoute: typeof CursoSlugCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests-ohm': {
      id: '/tests-ohm'
      path: '/tests-ohm'
      fullPath: '/tests-ohm'
      preLoaderRoute: typeof TestsOhmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teoria-ohm': {
      id: '/teoria-ohm'
      path: '/teoria-ohm'
      fullPath: '/teoria-ohm'
      preLoaderRoute: typeof TeoriaOhmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teoria-kirchhoff': {
      id: '/teoria-kirchhoff'
      path: '/teoria-kirchhoff'
      fullPath: '/teoria-kirchhoff'
      preLoaderRoute: typeof TeoriaKirchhoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curso/$slug/$courseId': {
      id: '/curso/$slug/$courseId'
      path: '/curso/$slug/$courseId'
      fullPath: '/curso/$slug/$courseId'
      preLoaderRoute: typeof CursoSlugCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeoriaKirchhoffRoute: TeoriaKirchhoffRoute,
  TeoriaOhmRoute: TeoriaOhmRoute,
  TestsOhmRoute: TestsOhmRoute,
  CategorySlugRoute: CategorySlugRoute,
  CursoSlugCourseIdRoute: CursoSlugCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
